### ISSUE TITLE
How can I help?

### ISSUE THREAD

**Issue by voltagex** [unofficial-bb8/docs#1]
I have a working BB-8 and an Android phone, plus at least one genuine BT4/LE dongle for my PC.

The Sphero SDK blink sample works for the BB-8 as long as you can wake it up first (by quickly switching from the official app). Some code for Android to wake the  BB-8 would be exceptionally useful.

**Comment by jubianchi** [comment]
Hi @voltagex !

I actually have a working nodejs sample which successfully wakes up BB-8. I will soon push that app so you can get the magic code to send to the robot to make it live ;)

**Comment by voltagex** [comment]
Any chance of pushing the code? I have captured traffic from the official app, and the commands look very similar to https://s3.amazonaws.com/docs.gosphero.com/api/Sphero_API_1.20.pdf, it even uses `011i3` as the developer mode string.
